### PR TITLE
Add entry for uarray.

### PR DESCRIPTION
**Pull request by hameerabbasi**
I was unable to find the list of sub-orgs. Is it listed somewhere?

### CODE REVIEW

**Comment by hameerabbasi** [comment]
In the e-mail it was mentioned that we're supposed to agree to the Python code of conduct, but where exactly do we indicate this? Adding a CoC file to the associated repo? In written somewhere on this repo?

**Comment by terriko** [comment]
List of sub-orgs: it's the "ideas list" here: https://python-gsoc.org/index.html#ideas
CoC: I believe we ask in the other registration system; you should have a link now!  But usually people just answer my email to confirm that it all works for them.

**Comment by hameerabbasi** [comment]
> List of sub-orgs: it's the "ideas list" here: https://python-gsoc.org/index.html#ideas

Must not have realized that contributing an idea counts as adding a sub-org to the website! That's what this PR is for. 👍

**Comment by terriko** [comment]
And you're on the page now, thank you!

**Pull request merged**
