### PR TITLE
Use official Pylons Project logo

### PR DESCRIPTION
**Pull request by stevepiercy**

### CODE REVIEW

**Comment by terriko** [comment]
@mmerickel Quick sanity check -- did you two agree on this as the final correct logo to have up? Are you ok with it being svg rather than a png like most of the other logos?

**Comment by mmerickel** [comment]
@terriko I trust Steve with the web assets. I think he's just cleaning up my mess!

**Comment by terriko** [comment]
Excellent, will merge.

**Comment by stevepiercy** [comment]
Thank you!

**Pull request merged**
