### PR TITLE
Update side-menu.css

### PR DESCRIPTION
**Pull request by soubhik-111**
I have modify the change to make the UI more better by changing the hover color of lists in Navigation side Bar.

### CODE REVIEW

**Comment by soubhik-111** [comment]
I have modified the UI by changing the color of hovering in navbar  @terriko mam can you please tell me whether it looks good or need to modify more ?

**Comment by terriko** [comment]
I'm taking the end of the year off from GSoC to focus on another software release, so you'll need to work with one of the other org admins if this needs to be merged before January.

**Comment by soubhik-111** [comment]
Okay, can you guide me how can I contribute on new software

**Comment by terriko** [comment]
No, as I said, I am personally not available to help people right now. There's lots of resources linked on our website, though: https://python-gsoc.org/ -- you might try one of our sub-orgs off the ideas page, some of those have a lot more active developers who might be less swamped with end of the year releases.

**Comment by terriko** [comment]
No one seems to be interested in having this change, so I'm going to close this issue.

**Pull request closed without merging**
