### PR TITLE
Add Borg collective links

### PR DESCRIPTION
**Pull request by m3nu**
Borg collective also joining again with new projects.

Thanks!

### CODE REVIEW

**Comment by warthog9** [comment]
Couple of minor update requests on your ideas page, GSoC has a pre-defined set of lengths of projects: 90, 175, 350

https://developers.google.com/open-source/gsoc/faq#how_much_time_does_gsoc_participation_take

Can you adjust your respective ideas to fit within those time frames I.E. switch 100 to 90, etc?

**Comment by warthog9** [comment]
Also looking forward to having you back this year!

**Comment by m3nu** [comment]
I can round those a bit. But last year we combined multiple projects into one full time project. So multiple tasks on the ideas page would sum up to one project for 350 hours (we only did full time last year).

**Comment by warthog9** [comment]
That makes sense, just make a note of that on the smaller ones so that there's a "here's a bit of a choose your own adventure projects of smaller things", I'm ok with that

**Comment by m3nu** [comment]
Great. I've emphasized this a bit more here at the top: https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2024-Ideas#project-ideas

> ... You can combine any number of tasks, so they add up to a full- or part time project.

**Comment by warthog9** [comment]
Another quick update I need done today if you can get to it, the project 
lengths need to be 90, 175, or 350.  Right now you've got "100 hours", 
"125-150 hours" etc  Those need to be noted as one of the 3 options. For 
the things that fall under the 3 (your 40, 80, etc) can you just go 
ahead and group them into a bigger project that fits into the 90/175/350?

**Comment by m3nu** [comment]
Sure thing. Will adjust it now.

**Comment by m3nu** [comment]
Done.

**Comment by warthog9** [comment]
Thanks!

**Pull request merged**
