### PR TITLE
Update MNE-Python URLs

### PR DESCRIPTION
**Pull request by cbrnr**
I've updated links for MNE-Python (@larsoner @drammock could you check if these are correct?).

### CODE REVIEW

**Comment by cbrnr** [comment]
Hmm, the changes in unrelated sections are probably whitespace corrections that my editor automatically applied. Let me know if you want me to revert these.

**Review by sappelhoff — APPROVED** [review]
I just checked, all links are good :+1: 

Thanks @cbrnr

**Comment by botanicvelious** [comment]
any url changes etc has to be setup by the mne gsoc suborg admin in the blogs interface unfortunately.

**Comment by larsoner** [comment]
I used this to attempt an update using the info from this PR:

https://blogs.python-gsoc.org/en/suborg/application/update/25/

Let me know if there is something else I need to do!

**Pull request closed without merging**
